const fmt = new Intl.NumberFormat('es-CO', { maximumFractionDigits: 0 });
const fmt1 = new Intl.NumberFormat('es-CO', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const fmtPct = new Intl.NumberFormat('es-CO', { minimumFractionDigits: 1, maximumFractionDigits: 1 });
let source;
const state = { mode: 'monthly', station: 'total', from: '', to: '' };
const stationCfg = {
  total: { label: 'Total red', fluidMonthly: 'fluids_bbl', fluidDaily: 'total_fluids_bbl' },
  jaguar: { label: 'Jaguar', fluidMonthly: 'fluids_jaguar_bbl', fluidDaily: 'fluids_jaguar_bbl' },
  ccs: { label: 'Caracara Sur', fluidMonthly: 'fluids_ccs_bbl', fluidDaily: 'fluids_ccs_bbl' },
};
const byId = (id) => document.getElementById(id);
const monthInRange = (month) => (!state.from || month >= state.from) && (!state.to || month <= state.to);
const dailyInRange = (day) => monthInRange(day.slice(0, 7));
const sum = (records, key) => records.reduce((acc, row) => acc + Number(row[key] || 0), 0);
const realIndexKey = () => state.mode === 'monthly' ? 'index_kwh_per_bbl' : 'energy_index_kwh_per_bbl';
const energyKey = () => state.mode === 'monthly' ? 'energy_kwh' : 'energy_kwh_imported_jaguar_ccs';
const fluidKey = () => state.mode === 'monthly' ? stationCfg[state.station].fluidMonthly : stationCfg[state.station].fluidDaily;
const filteredMonthly = () => source.monthly.filter((row) => monthInRange(row.month));
const filteredDaily = () => source.daily.filter((row) => dailyInRange(row.day));
function formatEnergy(value) { return value >= 1000000 ? `${fmt1.format(value / 1000000)} GWh` : `${fmt.format(value)} kWh`; }
function formatBbl(value) { return value >= 1000000 ? `${fmt1.format(value / 1000000)} MMbbl` : `${fmt.format(value)} bbl`; }
function setFilters() { const months = source.monthly.map((row) => row.month); state.from = months[0]; state.to = months[months.length - 1]; ['fromMonth','toMonth'].forEach((id) => { byId(id).min = state.from; byId(id).max = state.to; }); byId('fromMonth').value = state.from; byId('toMonth').value = state.to; }
function chartScales(values, width, height, padding) { const clean = values.map(Number).filter(Number.isFinite); const min = Math.min(...clean); const max = Math.max(...clean); const span = max - min || 1; return { x: (i, count) => padding.left + (count <= 1 ? 0 : i * (width - padding.left - padding.right) / (count - 1)), y: (v) => padding.top + (max - v) * (height - padding.top - padding.bottom) / span, min, max }; }
function lineChart(container, records, labelKey, valueKey, secondaryKey) {
  const el = byId(container); if (!records.length) { el.innerHTML = '<p>No hay datos para el periodo seleccionado.</p>'; return; }
  const width = 780, height = 310, padding = { top: 18, right: 28, bottom: 44, left: 54 };
  const p25 = source.totals.baseline_p25_kwh_per_bbl, p75 = source.totals.p75_kwh_per_bbl;
  const values = records.flatMap((row) => [Number(row[valueKey] || 0), secondaryKey ? Number(row[secondaryKey] || 0) : Number(row[valueKey] || 0), p25, p75]).filter(Boolean);
  const scale = chartScales(values, width, height, padding);
  const path = records.map((row, i) => `${i ? 'L' : 'M'}${scale.x(i, records.length).toFixed(1)},${scale.y(Number(row[valueKey] || 0)).toFixed(1)}`).join(' ');
  const secondaryPath = secondaryKey ? records.map((row, i) => `${i ? 'L' : 'M'}${scale.x(i, records.length).toFixed(1)},${scale.y(Number(row[secondaryKey] || 0)).toFixed(1)}`).join(' ') : '';
  const ticks = [scale.min, scale.min + (scale.max - scale.min) / 2, scale.max];
  const labels = records.length > 9 ? records.filter((_, i) => i === 0 || i === records.length - 1 || i === Math.floor(records.length / 2)) : records;
  el.innerHTML = `<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none">${ticks.map((tick) => `<line class="grid-line" x1="${padding.left}" x2="${width - padding.right}" y1="${scale.y(tick)}" y2="${scale.y(tick)}"></line>`).join('')}${ticks.map((tick) => `<text x="8" y="${scale.y(tick) + 4}" class="axis">${fmt1.format(tick)}</text>`).join('')}<line class="marker-p25" x1="${padding.left}" x2="${width - padding.right}" y1="${scale.y(p25)}" y2="${scale.y(p25)}"></line><line class="marker-p75" x1="${padding.left}" x2="${width - padding.right}" y1="${scale.y(p75)}" y2="${scale.y(p75)}"></line><path class="line-index" d="${path}"></path>${secondaryPath ? `<path class="line-secondary" d="${secondaryPath}"></path>` : ''}${labels.map((row) => { const i = records.indexOf(row); return `<text x="${scale.x(i, records.length)}" y="${height - 12}" text-anchor="${i === 0 ? 'start' : i === records.length - 1 ? 'end' : 'middle'}" class="axis">${row[labelKey]}</text>`; }).join('')}</svg>`;
}
function dualBarChart(container, records, aKey, bKey, aClass, bClass) {
  const el = byId(container); if (!records.length) { el.innerHTML = '<p>No hay datos para el periodo seleccionado.</p>'; return; }
  const width = 780, height = container === 'stationChart' ? 270 : 310, padding = { top: 18, right: 26, bottom: 44, left: 54 };
  const aVals = records.map((row) => Number(row[aKey] || 0) / 1000), bVals = records.map((row) => Number(row[bKey] || 0) / 1000);
  const max = Math.max(...aVals, ...bVals) || 1, group = (width - padding.left - padding.right) / records.length, bar = Math.max(3, Math.min(18, group / 3));
  const y = (v) => padding.top + (max - v) * (height - padding.top - padding.bottom) / max;
  const labels = records.length > 9 ? records.filter((_, i) => i === 0 || i === records.length - 1 || i === Math.floor(records.length / 2)) : records;
  el.innerHTML = `<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none">${[0, max / 2, max].map((tick) => `<line class="grid-line" x1="${padding.left}" x2="${width - padding.right}" y1="${y(tick)}" y2="${y(tick)}"></line><text x="8" y="${y(tick) + 4}" class="axis">${fmt.format(tick)}k</text>`).join('')}${records.map((row, i) => { const x = padding.left + i * group + group / 2; return `<rect class="${aClass}" x="${x - bar - 1}" y="${y(aVals[i])}" width="${bar}" height="${height - padding.bottom - y(aVals[i])}"></rect><rect class="${bClass}" x="${x + 1}" y="${y(bVals[i])}" width="${bar}" height="${height - padding.bottom - y(bVals[i])}"></rect>`; }).join('')}${labels.map((row) => { const i = records.indexOf(row); return `<text x="${padding.left + i * group + group / 2}" y="${height - 12}" text-anchor="${i === 0 ? 'start' : i === records.length - 1 ? 'end' : 'middle'}" class="axis">${row.month || row.day}</text>`; }).join('')}</svg>`;
}
function renderKpis() { const daily = filteredDaily(); const energy = sum(daily, 'energy_kwh_imported_jaguar_ccs'); const fluidsTotal = sum(daily, 'total_fluids_bbl'); const viewFluids = sum(daily, stationCfg[state.station].fluidDaily); const index = fluidsTotal ? energy / fluidsTotal : 0; const saving = Math.max(0, (index - source.totals.baseline_p25_kwh_per_bbl) * fluidsTotal); byId('kpiIndex').textContent = fmt1.format(index); byId('kpiEnergy').textContent = formatEnergy(energy); byId('kpiFluids').textContent = formatBbl(viewFluids); byId('kpiSavings').textContent = formatEnergy(saving); byId('kpiFluidLabel').textContent = state.station === 'total' ? 'Fluidos movidos' : `Fluidos ${stationCfg[state.station].label}`; byId('kpiFluidHelp').textContent = state.station === 'total' ? 'Crudo + agua inyectada' : 'Vista por estacion, no indice electrico medido'; byId('periodLabel').textContent = `${source.period.start} a ${source.period.end} · ${source.period.days} dias fuente`; }
function renderMethodAlert() { byId('methodAlert').innerHTML = state.station === 'total' ? '<strong>Indice energetico real:</strong> energia importada total de red dividida entre fluidos Jaguar + Caracara Sur. Toro Sentado esta excluido.' : `<strong>${stationCfg[state.station].label}:</strong> la fuente electrica no trae consumo separado por estacion. Esta vista analiza fluidos y participacion; no recalcula el indice usando toda la energia de red contra una sola estacion.`; }
function renderCharts() { const records = state.mode === 'monthly' ? filteredMonthly() : filteredDaily(); lineChart('indexChart', records, state.mode === 'monthly' ? 'month' : 'day', realIndexKey(), state.mode === 'daily' ? 'rolling_7d_index' : null); dualBarChart('energyFluidChart', records, energyKey(), fluidKey(), 'bar-energy', 'bar-fluid'); dualBarChart('stationChart', records, 'fluids_ccs_bbl', 'fluids_jaguar_bbl', 'bar-ccs', 'bar-jaguar'); renderTrendSignal(records); byId('trendCopy').textContent = state.station === 'total' ? 'Indice consolidado de la red importada. Menor valor indica mejor eficiencia.' : 'La linea conserva el indice real consolidado; la estacion seleccionada cambia los fluidos y la lectura operativa.'; byId('energyFluidCopy').textContent = state.station === 'total' ? 'Energia importada frente a fluidos totales Jaguar + CCS.' : `Energia total de red frente a fluidos de ${stationCfg[state.station].label}; es una vista de carga relativa, no indice medido por estacion.`; }
function renderTrendSignal(records) { const el = byId('trendSignal'); const key = realIndexKey(); const last = records[records.length - 1], prev = records[records.length - 2]; if (!last || !prev) { el.textContent = 'Sin comparativo'; el.className = 'signal'; return; } const delta = ((Number(last[key]) / Number(prev[key])) - 1) * 100; el.textContent = `${delta >= 0 ? '+' : ''}${fmtPct.format(delta)}% vs anterior`; el.className = `signal ${delta > 2 ? 'bad' : delta < -2 ? 'good' : 'warn'}`; }
function renderFindings() { const totals = source.totals, latest = source.highlights.latest_month, best = source.highlights.best_month, worst = source.highlights.worst_month, change = source.highlights.period_change_pct_first_to_latest, corr = source.highlights.correlation_energy_vs_fluids; const daily = filteredDaily(); const viewFluids = sum(daily, stationCfg[state.station].fluidDaily), totalFluids = sum(daily, 'total_fluids_bbl'), share = totalFluids ? viewFluids / totalFluids * 100 : 0; const stationText = state.station === 'total' ? `El indice ponderado del periodo completo es <strong>${fmt1.format(totals.weighted_index_kwh_per_bbl)} kWh/bbl</strong>, con ${formatEnergy(totals.energy_kwh)} y ${formatBbl(totals.fluids_bbl)}.` : `${stationCfg[state.station].label} representa <strong>${fmtPct.format(share)}%</strong> de los fluidos del periodo filtrado. Para indice por estacion se necesita medicion electrica separada o una regla formal de asignacion.`; byId('executiveFindings').innerHTML = [stationText, `El mejor mes fue <strong>${best.month}</strong> con ${fmt1.format(best.index_kwh_per_bbl)} kWh/bbl; el peor fue <strong>${worst.month}</strong> con ${fmt1.format(worst.index_kwh_per_bbl)} kWh/bbl.`, `Entre el primer mes y ${latest.month} el indice mensual ${change > 0 ? 'subio' : 'bajo'} <strong>${fmtPct.format(Math.abs(change))}%</strong>.`, `La correlacion energia-fluidos es <strong>${fmt1.format(corr)}</strong>; hay cargas base o condiciones operativas que no siguen perfectamente el volumen.`].map((item) => `<li>${item}</li>`).join(''); }
function renderAlerts() { const records = filteredDaily(); const p75 = source.totals.p75_kwh_per_bbl, p25 = source.totals.baseline_p25_kwh_per_bbl; const high = records.filter((row) => Number(row.energy_index_kwh_per_bbl) > p75).length, low = records.filter((row) => Number(row.energy_index_kwh_per_bbl) <= p25).length; const totalFluids = sum(records, 'total_fluids_bbl'), viewFluids = sum(records, stationCfg[state.station].fluidDaily), share = totalFluids ? viewFluids / totalFluids * 100 : 0; byId('alerts').innerHTML = [`<div class="alert-item ${high ? 'bad' : 'good'}"><strong>${high} dias sobre P75.</strong><br>Validar equipos en servicio, recirculaciones, restricciones y presiones de inyeccion.</div>`, `<div class="alert-item good"><strong>${low} dias en zona P25.</strong><br>Usarlos como referencia interna alcanzable para comparar condiciones operativas.</div>`, `<div class="alert-item"><strong>${fmtPct.format(share)}% de fluidos en la vista.</strong><br>${state.station === 'total' ? 'Alcance completo Jaguar + CCS.' : 'Participacion operacional de la estacion seleccionada.'}</div>`].join(''); }
function renderOpportunities() { const totals = source.totals; byId('opportunities').innerHTML = [`Cruzar los dias sobre P75 (${fmt1.format(totals.p75_kwh_per_bbl)} kWh/bbl) con bitacora, bombas en servicio, presion de descarga y eventos de mantenimiento.`, 'Separar medicion electrica por barra, alimentador o centro de carga para calcular indice real Jaguar y CCS sin imputaciones.', 'Revisar consumo base: la correlacion energia-fluidos menor a 1 indica que parte de la demanda no depende directamente del volumen movido.', 'Mantener Toro Sentado fuera del calculo de red para no mezclar energia local con energia importada.'].map((item) => `<li>${item}</li>`).join(''); }
function renderPercentiles() { byId('percentileBox').innerHTML = `<div><span>P25 referencia</span><strong>${fmt1.format(source.totals.baseline_p25_kwh_per_bbl)}</strong></div><div><span>P75 alerta</span><strong>${fmt1.format(source.totals.p75_kwh_per_bbl)}</strong></div><div><span>Promedio diario</span><strong>${fmt1.format(source.totals.avg_index_kwh_per_bbl)}</strong></div><div><span>Ponderado</span><strong>${fmt1.format(source.totals.weighted_index_kwh_per_bbl)}</strong></div>`; }
function renderTables() { const fKey = stationCfg[state.station].fluidMonthly; byId('monthlyTable').innerHTML = filteredMonthly().slice().reverse().map((row) => `<tr><td>${row.month}</td><td>${fmt1.format(row.index_kwh_per_bbl)}</td><td>${formatEnergy(row.energy_kwh)}</td><td>${formatBbl(row[fKey])}</td><td>${row.delta_vs_prev_pct == null || row.delta_vs_prev_pct === '' ? '-' : `${fmtPct.format(row.delta_vs_prev_pct)}%`}</td></tr>`).join(''); byId('criticalDays').innerHTML = source.high_index_days.filter((row) => dailyInRange(row.day)).slice(0, 10).map((row) => `<tr><td>${row.day}</td><td>${fmt1.format(row.energy_index_kwh_per_bbl)}</td><td>${formatEnergy(row.energy_kwh_imported_jaguar_ccs)}</td><td>${formatBbl(row.total_fluids_bbl)}</td></tr>`).join(''); }
function render() { renderMethodAlert(); renderKpis(); renderCharts(); renderFindings(); renderAlerts(); renderOpportunities(); renderPercentiles(); renderTables(); }
async function init() { const response = await fetch('./data.json?v=20260915-exec1', { cache: 'no-store' }); source = await response.json(); setFilters(); render(); byId('viewMode').addEventListener('change', (event) => { state.mode = event.target.value; render(); }); document.querySelectorAll('[data-station]').forEach((button) => { button.addEventListener('click', () => { state.station = button.dataset.station; document.querySelectorAll('[data-station]').forEach((item) => item.classList.toggle('active', item === button)); render(); }); }); byId('fromMonth').addEventListener('change', (event) => { state.from = event.target.value; if (state.to < state.from) { state.to = state.from; byId('toMonth').value = state.to; } render(); }); byId('toMonth').addEventListener('change', (event) => { state.to = event.target.value; if (state.from > state.to) { state.from = state.to; byId('fromMonth').value = state.from; } render(); }); byId('resetFilters').addEventListener('click', () => { setFilters(); state.mode = 'monthly'; state.station = 'total'; byId('viewMode').value = 'monthly'; document.querySelectorAll('[data-station]').forEach((item) => item.classList.toggle('active', item.dataset.station === 'total')); render(); }); }
init().catch((error) => { document.body.innerHTML = `<main class="panel"><h1>No se pudo cargar el dashboard</h1><p>${error.message}</p></main>`; });
