'use strict';
const $=id=>document.getElementById(id),E=CostEngine,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=new Intl.NumberFormat('es-CO',{maximumFractionDigits:0}),money=new Intl.NumberFormat('es-CO',{minimumFractionDigits:2,maximumFractionDigits:2});
const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const labels={req:'Solicitante de PO · Requisitioner',period:'Periodo fiscal',profit:'Centro de beneficio',station:'Estación / ámbito',area:'Área',vendor:'Proveedor',category:'Subcategoría',account:'Cuenta contable',costCenter:'Centro de costo',planner:'Grupo planificador',ot:'Orden de trabajo · OT',po:'Pedido de compra · PO',kind:'Servicio / repuesto',docType:'Tipo de documento',otType:'Tipo de OT',workCenter:'Puesto de trabajo',equipment:'Equipo SAP',status:'Estado OT (IW39)',priority:'Prioridad OT',functionalArea:'Área funcional',contract:'Contrato OLA'};
const detailLabels={period:'Periodo fiscal',date:'Fecha contabilización',documentDate:'Fecha documento',usd:'Importe USD',cop:'Importe COP',req:'Solicitante PO (Requisitioner)',station:'Estación / ámbito',area:'Área',vendor:'Proveedor',vendorId:'Número proveedor',account:'Cuenta',accountName:'Nombre cuenta',costCenter:'Centro de costo',costCenterName:'Nombre centro de costo',po:'Pedido PO',poLine:'Posición PO',ot:'Orden de trabajo',otName:'Descripción OT',doc:'Documento contable',docLine:'Posición documento',docType:'Tipo documento',docTypeName:'Nombre tipo documento',description:'Descripción movimiento',category:'Subcategoría',kind:'Servicio / repuesto',profit:'Centro de beneficio',planner:'Grupo planificador',plannerName:'Nombre grupo planificador',location:'Ubicación funcional',locationName:'Nombre ubicación',workCenter:'Puesto de trabajo',workCenterName:'Nombre puesto',contract:'Contrato OLA',material:'Material',materialName:'Nombre material',currency:'Moneda transacción',transactionAmount:'Importe transacción',functionalArea:'Área funcional',otType:'Tipo OT',invoice:'Factura',ses:'Entrada de servicio',equipment:'Equipo SAP (IW39)',equipmentName:'Descripción equipo',status:'Estado OT (IW39)',priority:'Prioridad OT',otCreated:'Creación OT',matchedOT:'Coincide con IW39',review:'Asignación en revisión'};
let data=[],meta={},filtered=[],currency='usd',page=0,pageSize=25,sortKey='usd',sortDir=-1,currentView='overview',timer;
const state={dims:{},search:'',review:'all',from:'',to:'',sign:'all',otMatch:'all',min:'',max:''};
const controls={};
function fmt(v){return money.format(v||0)}function compact(v){const a=Math.abs(v);return (v<0?'−':'')+(a>=1e9?(a/1e9).toLocaleString('es-CO',{maximumFractionDigits:2})+' mil M':a>=1e6?(a/1e6).toLocaleString('es-CO',{maximumFractionDigits:2})+' M':a>=1e3?(a/1e3).toLocaleString('es-CO',{maximumFractionDigits:1})+' mil':nf.format(a));}
function percent(v,total){return Math.abs(total)<.005?'—':(v/total*100).toLocaleString('es-CO',{maximumFractionDigits:1})+' %'}
function labelFor(key,v){if(key==='period')return months[Number(v)-1]+' 2026';const names={account:'accountName',costCenter:'costCenterName',ot:'otName',equipment:'equipmentName',planner:'plannerName',workCenter:'workCenterName'};if(names[key]){const r=data.find(r=>E.clean(r[key])===v);return v+(r?.[names[key]]?' · '+r[names[key]]:'');}return v;}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,6000)}
function addFilter(key,target){
 state.dims[key]=new Set();const counts=new Map();for(const r of data){let v=E.clean(r[key]);counts.set(v,(counts.get(v)||0)+1)}
 const values=[...counts.keys()].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));if(key==='req'){values.sort((a,b)=>a==='Sin solicitante'?-1:b==='Sin solicitante'?1:a.localeCompare(b));}
 const box=document.createElement('div');box.innerHTML=`<label class="filter-label" id="lbl-${key}">${esc(labels[key])}</label><details class="multi"><summary aria-labelledby="lbl-${key} sum-${key}"><span class="summary-text" id="sum-${key}">Todos</span><span aria-hidden="true">⌄</span></summary><div class="popover"><input type="search" placeholder="Buscar ${key==='req'?'solicitante':'opción'}…" aria-label="Buscar en ${esc(labels[key])}"><div class="option-actions"><button type="button" class="text-button" data-act="visible">Seleccionar visibles</button><button type="button" class="text-button" data-act="clear">Todos / limpiar</button></div><div class="options"></div><p class="hint">Selección múltiple · opciones de toda la base.</p></div></details>`;
 $(target).append(box);const details=box.querySelector('details'),search=box.querySelector('input'),opts=box.querySelector('.options');
 const options=values.map(v=>({v,label:labelFor(key,v),n:counts.get(v)}));let visible=options;
 function draw(){const q=search.value.toLocaleLowerCase('es');visible=options.filter(o=>o.label.toLocaleLowerCase('es').includes(q));opts.innerHTML=visible.map((o,i)=>`<label class="option"><input type="checkbox" data-i="${i}" ${state.dims[key].has(o.v)?'checked':''}><span class="label">${esc(o.label)}</span><small>${nf.format(o.n)}</small></label>`).join('')||'<p class="hint">Sin coincidencias.</p>';}
 function sync(){const set=state.dims[key];box.querySelector('.summary-text').textContent=set.size===0?'Todos':set.size===1?labelFor(key,[...set][0]):`${set.size} seleccionados`;details.classList.toggle('selected',!!set.size);if(details.open)draw();}
 search.addEventListener('input',draw);opts.addEventListener('change',e=>{if(!e.target.matches('input'))return;const v=visible[Number(e.target.dataset.i)].v;e.target.checked?state.dims[key].add(v):state.dims[key].delete(v);sync();refresh()});
 box.querySelector('[data-act=clear]').onclick=()=>{state.dims[key].clear();sync();draw();refresh()};box.querySelector('[data-act=visible]').onclick=()=>{visible.forEach(o=>state.dims[key].add(o.v));sync();draw();refresh()};
 details.addEventListener('toggle',()=>{if(details.open){document.querySelectorAll('.multi[open]').forEach(d=>{if(d!==details)d.open=false});draw();search.focus()}});controls[key]={sync,details};
}
function setDim(key,value){state.dims[key]=new Set([value]);controls[key].sync();refresh();}
function reset(){Object.values(state.dims).forEach(s=>s.clear());Object.assign(state,{search:'',review:'all',from:'',to:'',sign:'all',otMatch:'all',min:'',max:''});for(const [id,key] of Object.entries(bindings))$(id).value=state[key];Object.values(controls).forEach(c=>c.sync());refresh();}
const bindings={'search':'search','review':'review','date-from':'from','date-to':'to','sign':'sign','ot-match':'otMatch','amount-min':'min','amount-max':'max'};
function chips(){let html='';for(const [key,s]of Object.entries(state.dims))if(s.size)html+=`<span class="chip">${esc(labels[key])}: ${esc([...s].slice(0,3).join(', '))}${s.size>3?' +'+(s.size-3):''}<button data-key="${key}" aria-label="Eliminar filtro ${esc(labels[key])}">×</button></span>`;
 const extras={search:state.search,review:state.review==='all'?'':state.review==='exclude'?'Sin asignación en revisión':'Solo asignación en revisión',from:state.from,to:state.to,sign:state.sign==='all'?'':state.sign==='positive'?'Cargos positivos':state.sign==='negative'?'Abonos negativos':'Importe cero',otMatch:state.otMatch==='all'?'':state.otMatch==='matched'?'Con OT IW39':state.otMatch==='zero'?'OT cero':'Sin OT IW39',min:state.min,max:state.max};
 const extraNames={search:'Búsqueda',review:'Asignación',from:'Desde',to:'Hasta',sign:'Movimiento',otMatch:'Vínculo OT',min:'Importe mínimo',max:'Importe máximo'};
 for(const [key,v]of Object.entries(extras))if(v!=='')html+=`<span class="chip">${extraNames[key]}: ${esc(v)}<button data-extra="${key}" aria-label="Eliminar ${extraNames[key]}">×</button></span>`;
 $('active-filters').innerHTML=html;
}
let persistScope=()=>{};
function refresh(){persistScope();page=0;filtered=data.filter(r=>E.match(r,state,currency));chips();render();}
function render(){
 const total=E.sum(filtered,currency),base=E.sum(data,currency),positive=E.sum(filtered.filter(r=>r[currency]>0),currency),negative=E.sum(filtered.filter(r=>r[currency]<0),currency);const missing=filtered.filter(r=>r.req==='Sin solicitante'),reviewRows=filtered.filter(r=>r.review);
 $('selection-count').innerHTML=`<strong>${nf.format(filtered.length)}</strong> de ${nf.format(data.length)} movimientos · ${percent(total,base)} del neto de la base`;
 const periods=[...new Set(filtered.map(r=>r.period))].sort();$('selection-scope').textContent=periods.length?`${periods.length} periodo${periods.length>1?'s':''} · ${currency.toUpperCase()}`:'Sin resultados';
 $('empty').hidden=!!filtered.length;$('results').hidden=!filtered.length;$('export').disabled=!filtered.length;
 $('k-net').textContent=compact(total);$('k-net-note').textContent=fmt(total)+' '+currency.toUpperCase();$('k-positive').textContent=compact(positive);$('k-negative').textContent='Abonos / reversos: '+compact(negative)+' '+currency.toUpperCase();
 const ots=new Set(filtered.filter(r=>Number(r.ot)).map(r=>r.ot)),pos=new Set(filtered.filter(r=>Number(r.po)).map(r=>r.po));$('k-orders').textContent=nf.format(ots.size)+' / '+nf.format(pos.size);
 $('k-missing').textContent=percent(missing.length,filtered.length);$('k-missing-note').textContent=nf.format(missing.length)+' movimientos · '+compact(E.sum(missing,currency))+' '+currency.toUpperCase();
 $('review-banner').hidden=!reviewRows.length;$('review-title').textContent=compact(E.sum(reviewRows,currency))+' '+currency.toUpperCase()+' de la selección están en revisión';$('review-description').textContent=`${nf.format(reviewRows.length)} movimientos · Cuenta 69901000 · 24 ago 2026. Incluidos en el neto; pendiente de conciliación con Finanzas/CO.`;
 if(currentView==='overview'){renderTrend();renderRanking();renderReq(total)}if(currentView==='detail')renderTable();if(currentView==='quality')renderQuality();
}
function renderTrend(){
 const gs=E.groups(filtered,'period',currency),map=new Map(gs.map(g=>[g.name,g])),vals=months.map((_,i)=>map.get(String(i+1).padStart(3,'0'))?.value||0),max=Math.max(...vals,0),min=Math.min(...vals,0);let span=max-min||1,pad=span*.13;const hi=max+pad,lo=min<0?min-pad:0,W=650,H=250,left=65,right=15,top=20,bottom=35,y=v=>top+(hi-v)/(hi-lo)*(H-top-bottom),step=(W-left-right)/12;
 let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Gasto neto mensual en ${currency.toUpperCase()}">`;
 for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;svg+=`<line x1="${left}" x2="${W-right}" y1="${y(v)}" y2="${y(v)}" stroke="#e9eef3"/><text x="${left-10}" y="${y(v)+4}" text-anchor="end">${esc(compact(v))}</text>`;}
 svg+=`<line x1="${left}" x2="${W-right}" y1="${y(0)}" y2="${y(0)}" stroke="#b4c4d1"/>`;
 months.forEach((m,i)=>{const period=String(i+1).padStart(3,'0'),g=map.get(period),v=vals[i],x=left+i*step+12,width=step-24;svg+=`<g class="month" tabindex="0" role="button" data-period="${period}" aria-label="Filtrar ${m} 2026: ${esc(fmt(v))} ${currency.toUpperCase()}"><title>${m} 2026: ${esc(fmt(v))} ${currency.toUpperCase()} · ${g?.n||0} movimientos</title><rect x="${x}" y="${Math.min(y(v),y(0))}" width="${width}" height="${Math.max(Math.abs(y(v)-y(0)),2)}" rx="3" fill="${g?.review?'#c1903f':'#168793'}"/><text x="${x+width/2}" y="${H-12}" text-anchor="middle">${m}</text></g>`});svg+='</svg>';$('trend').innerHTML=svg;$('chart-unit').textContent=currency.toUpperCase()+' · neto';
}
function renderRanking(){const key=$('ranking-dim').value,gs=E.groups(filtered,key,currency).slice(0,8),max=Math.max(...gs.map(g=>Math.abs(g.value)),1);$('ranking').innerHTML=gs.map((g,i)=>`<button class="ranking-row" data-key="${key}" data-value="${esc(g.name)}" title="Filtrar ${esc(labelFor(key,g.name))}"><div><div class="rank-title"><small>${String(i+1).padStart(2,'0')}</small><span>${esc(labelFor(key,g.name))}</span></div><div class="rank-track"><i style="width:${Math.abs(g.value)/max*100}%"></i></div></div><div class="rank-value">${esc(compact(g.value))}<small>${nf.format(g.n)} movimientos</small></div></button>`).join('');}
function renderReq(total){const gs=E.groups(filtered,'req',currency),max=Math.max(...gs.map(g=>Math.abs(g.value)),1);$('req-coverage').textContent=gs.filter(g=>g.name!=='Sin solicitante').length+' solicitantes identificados';$('req-table').innerHTML=gs.map(g=>`<tr><td><button class="req-name" data-value="${esc(g.name)}">${esc(g.name)}</button></td><td class="num">${nf.format(g.n)}</td><td class="num">${nf.format(g.pos.size)}</td><td class="num">${fmt(g.value)}</td><td class="num">${percent(g.value,total)}</td><td><span class="table-bar"><i style="width:${Math.abs(g.value)/max*100}%"></i></span></td></tr>`).join('');}
const tableCols=[['date','Contabilización'],['req','Solicitante PO'],['po','PO'],['ot','OT'],['station','Estación'],['vendor','Proveedor'],['account','Cuenta'],['description','Descripción'],['amount','Importe'],['review','Revisión']];
function renderTable(){const rows=[...filtered].sort((a,b)=>{const av=a[sortKey],bv=b[sortKey];return(typeof av==='number'?av-(bv||0):String(av??'').localeCompare(String(bv??''),'es',{numeric:true}))*sortDir}),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages-1);const shown=rows.slice(page*pageSize,(page+1)*pageSize);$('transactions').querySelector('thead').innerHTML='<tr>'+tableCols.map(([k,l])=>`<th class="${k==='amount'?'num':''}"><button class="sort" data-sort="${k==='amount'?currency:k}">${l}${k==='amount'?' '+currency.toUpperCase():''} ${sortKey===(k==='amount'?currency:k)?sortDir===1?'↑':'↓':'↕'}</button></th>`).join('')+'</tr>';
 $('transactions').querySelector('tbody').innerHTML=shown.map(r=>`<tr class="transactions-row" data-row="${r._id}" tabindex="0" aria-label="Abrir documento ${esc(r.doc)} posición ${esc(r.docLine)}">${tableCols.map(([k])=>`<td class="${k==='amount'?'num':''}" title="${esc(k==='amount'?fmt(r[currency]):r[k])}">${k==='amount'?fmt(r[currency]):k==='review'?r.review?'<span class="flag">En revisión</span>':'—':esc(r[k]??'—')}</td>`).join('')}</tr>`).join('');
 $('page-info').textContent=`${rows.length?page*pageSize+1:0}–${Math.min((page+1)*pageSize,rows.length)} de ${nf.format(rows.length)} · Página ${page+1} de ${pages}`;$('prev').disabled=page===0;$('next').disabled=page>=pages-1;
}
function renderQuality(){const groups=[['Sin solicitante de PO',filtered.filter(r=>r.req==='Sin solicitante')],['Sin coincidencia con IW39',filtered.filter(r=>!r.matchedOT)],['Número de OT cero',filtered.filter(r=>!Number(r.ot))],['Estación “POR REVISAR”',filtered.filter(r=>r.station==='POR REVISAR')],['Asignación en revisión',filtered.filter(r=>r.review)],['Último periodo cargado (no acredita cierre)',filtered.filter(r=>r.period===[...new Set(data.map(x=>x.period))].sort().at(-1))]];$('quality-metrics').innerHTML=groups.map(([l,rs])=>`<div class="quality-metric"><span>${l}</span><strong>${nf.format(rs.length)} filas<br>${compact(E.sum(rs,currency))} ${currency.toUpperCase()}</strong></div>`).join('');}
function view(name){currentView=name;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==name);document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));render();}
function openRow(id){const r=data[id];$('row-title').textContent=`Documento ${r.doc} · posición ${r.docLine}`;$('row-content').innerHTML='<div class="detail-grid">'+Object.entries(detailLabels).map(([k,l])=>`<div class="detail-item"><span>${esc(l)}</span><strong>${esc(typeof r[k]==='boolean'?r[k]?'Sí':'No':['usd','cop','transactionAmount'].includes(k)?fmt(r[k]):r[k]??'Sin dato')}</strong></div>`).join('')+'</div>';$('row-dialog').showModal();}
function exportCSV(){const keys=Object.keys(detailLabels),safe=v=>{let s=String(v??'');if(typeof v==='string'&&/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const content=[keys.map(k=>safe(detailLabels[k])).join(';'),...filtered.map(r=>keys.map(k=>safe(r[k])).join(';'))].join('\r\n');const blob=new Blob(['\ufeff'+content],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Gastos_mantenimiento_seleccion_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`${nf.format(filtered.length)} movimientos exportados con importes USD y COP.`);}
async function init(){try{
 const res=await fetch('data.json');if(!res.ok)throw Error('No se pudo cargar la base');meta=await res.json();data=meta.rows.map((r,i)=>Object.assign(Object.fromEntries(meta.columns.map((k,j)=>[k,r[j]])),{_id:i}));
 if(data.length!==meta.rowCount||Math.abs(E.sum(data,'usd')-meta.totalUSD)>.05)throw Error('La base no coincide con los totales verificados');
 addFilter('req','req-filter');for(const key of ['period','profit','station','area','vendor','category'])addFilter(key,'main-filters');for(const key of ['account','costCenter','planner','ot','po','kind','docType','otType','workCenter','equipment','status','priority','functionalArea','contract'])addFilter(key,'extra-filters');
 for(const [id,key]of Object.entries(bindings))$(id).addEventListener(id==='search'?'input':'change',()=>{state[key]=$(id).value;if(id==='search'){clearTimeout(searchTimer);searchTimer=setTimeout(refresh,160)}else refresh()});
 $('currency').onchange=()=>{currency=$('currency').value;if(sortKey==='usd'||sortKey==='cop')sortKey=currency;refresh()};$('reset').onclick=reset;$('empty-reset').onclick=reset;$('export').onclick=exportCSV;
 $('advanced-toggle').onclick=()=>{const open=$('advanced').hidden;$('advanced').hidden=!open;$('advanced-toggle').setAttribute('aria-expanded',String(open));$('advanced-toggle').innerHTML=open?'Menos filtros −':'Más filtros ＋'};
 $('active-filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.key){state.dims[b.dataset.key].clear();controls[b.dataset.key].sync()}else{const key=b.dataset.extra;state[key]=['review','sign','otMatch'].includes(key)?'all':'';$(Object.keys(bindings).find(id=>bindings[id]===key)).value=state[key]}refresh()};
 $('exclude-review').onclick=()=>{state.review='exclude';$('review').value='exclude';refresh()};$('ranking-dim').onchange=renderRanking;
 $('ranking').onclick=e=>{const b=e.target.closest('[data-value]');if(b)setDim(b.dataset.key,b.dataset.value)};$('req-table').onclick=e=>{const b=e.target.closest('[data-value]');if(b)setDim('req',b.dataset.value)};
 const chartClick=e=>{const g=e.target.closest('[data-period]');if(g)setDim('period',g.dataset.period)};$('trend').onclick=chartClick;$('trend').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chartClick(e)}};
 document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>view(b.dataset.view));$('quality-link').onclick=()=>view('quality');
 $('transactions').onclick=e=>{const b=e.target.closest('[data-sort]');if(b){if(sortKey===b.dataset.sort)sortDir*=-1;else{sortKey=b.dataset.sort;sortDir=1}renderTable();return}const tr=e.target.closest('[data-row]');if(tr)openRow(Number(tr.dataset.row))};$('transactions').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-row]')){e.preventDefault();openRow(Number(e.target.dataset.row))}};
 $('prev').onclick=()=>{page--;renderTable()};$('next').onclick=()=>{page++;renderTable()};$('page-size').onchange=()=>{pageSize=Number($('page-size').value);page=0;renderTable()};$('close-dialog').onclick=()=>$('row-dialog').close();$('row-dialog').onclick=e=>{if(e.target===$('row-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
 $('maintenance-preset').onclick=()=>{state.dims.req=new Set(['GRAJALEJ','CHIPIAJH','SALANUEF','SANDOVAF']);controls.req.sync();refresh();toast('Regla M aplicada. SALANUEF y SANDOVAF no tienen movimientos en esta base. No es una lista exhaustiva de mantenimiento.')};
 const savedFilterKey='mnt-scope-filters-v2';
 function readSavedScope(){
  const raw=localStorage.getItem(savedFilterKey);
  if(raw){const value=JSON.parse(raw);if(!value||!['req','area','profit'].every(k=>Array.isArray(value[k])&&value[k].every(v=>typeof v==='string')))throw Error('Preferencias inválidas');return value;}
  const legacy=localStorage.getItem('mnt-requisitioners-v1');
  if(legacy){const req=JSON.parse(legacy);if(!Array.isArray(req)||!req.every(v=>typeof v==='string'))throw Error('Preferencias inválidas');return {req,area:[],profit:[]};}
  return null;
 }
 function applySavedScope(scope){for(const key of ['req','area','profit']){state.dims[key]=new Set(scope[key]);controls[key].sync();}}
 $('save-req').onclick=()=>{try{const scope=Object.fromEntries(['req','area','profit'].map(k=>[k,[...state.dims[k]]]));localStorage.setItem(savedFilterKey,JSON.stringify(scope));$('load-req').hidden=false;toast('Solicitantes, área y centro de beneficio guardados. Se aplicarán al volver a abrir este tablero.')}catch{toast('Este navegador no permite guardar preferencias.')}};
 $('load-req').onclick=()=>{try{const scope=readSavedScope();if(scope){applySavedScope(scope);refresh();toast('Filtros guardados de solicitante, área y centro de beneficio aplicados.')}}catch{toast('No se pudo recuperar la selección guardada.')}};
 try{const scope=readSavedScope();$('load-req').hidden=!scope;if(scope)applySavedScope(scope);}catch{toast('No se pudieron leer los filtros guardados; puedes guardar una nueva selección.');}
 persistScope=()=>{try{
  const scope=Object.fromEntries(['req','area','profit'].map(k=>[k,[...state.dims[k]]]));
  localStorage.setItem(savedFilterKey,JSON.stringify(scope));
  $('save-req').textContent='Guardado automático ✓';
  $('save-req').title='Solicitante, área y centro de beneficio guardados en este navegador';
  $('load-req').hidden=true;
 }catch{
  $('save-req').textContent='No se pudo guardar';
  $('save-req').title='El navegador está bloqueando el almacenamiento local. Mantén el mismo archivo y evita el modo privado.';
 }};

 document.addEventListener('click',e=>{document.querySelectorAll('.multi[open]').forEach(d=>{if(!d.contains(e.target))d.open=false})});document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.multi[open]').forEach(d=>{d.open=false;d.querySelector('summary').focus()})});
 const cutoff=meta.cutoff||'No disponible';
 $('data-freshness').textContent='Carga ODS máxima: '+cutoff+' · Contabilización máxima: '+(meta.postingMax||data.map(r=>r.date).sort().at(-1))+' · Archivo: '+meta.source;
 $('generated-at').textContent=meta.generatedAt?'Tablero generado: '+new Date(meta.generatedAt).toLocaleString('es-CO'):'Versión inicial';
 $('rail-cutoff').textContent='Carga ODS máxima: '+cutoff;
 for(const id of ['date-from','date-to']){$(id).min=data.map(r=>r.date).sort()[0];$(id).max=data.map(r=>r.date).sort().at(-1)}
 $('loading').hidden=true;$('app').hidden=false;refresh();
 }catch(e){$('loading').innerHTML='<h2>No pudimos cargar los gastos</h2><p>Recarga la página para volver a intentarlo.</p>';$('loading').setAttribute('role','alert');console.error(e)}}
let searchTimer;init();
